name: Find FPRJ Files
on:
  workflow_dispatch: # 允许手动触发
  repository_dispatch: # 允许通过API触发
    types: [find-fprj-request]

jobs:
  find-fprj:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Find .fprj files
        id: find-files
        run: |
          # 递归查找所有.fprj文件并保存为JSON数组
          find . -type f -name "*.fprj" | jq -R -s 'split("\n") | map(select(. != ""))' > fprj_files.json
          echo "Found $(jq length fprj_files.json) .fprj files"

      - name: Prepare JSON response
        id: prepare-response
        run: |
          # 创建包含完整响应的JSON文件
          jq -n \
            --arg run_id "$GITHUB_RUN_ID" \
            --arg timestamp "$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
            --slurpfile files fprj_files.json \
            '{
              status: "success",
              run_id: $run_id,
              timestamp: $timestamp,
              file_count: ($files[0] | length),
              files: $files[0]
            }' > response.json
          
          # 打印结果便于调试
          echo "Response JSON:"
          cat response.json

      - name: Send results
        run: |
          # 从仓库的secrets获取用户API端点
          API_URL="${{ secrets.RESULT_API_URL }}"
          
          # 直接使用文件发送POST请求
          curl -X POST "$API_URL" \
            -H "Content-Type: application/json" \
            --data-binary "@response.json"
