name: Find FPRJ Files
on:
  workflow_dispatch:
  repository_dispatch:
    types: [find-fprj-request]

jobs:
  find-fprj:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.set-output.outputs.result }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Find .fprj files
        run: |
          # 递归查找所有.fprj文件
          find . -type f -name "*.fprj" > file_list.txt
          jq -R -s 'split("\n") | map(select(. != ""))' file_list.txt > fprj_files.json
          echo "Found $(jq -r 'length' fprj_files.json) .fprj files"

      - name: Prepare JSON result
        run: |
          jq -n \
            --arg run_id "$GITHUB_RUN_ID" \
            --arg timestamp "$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
            --slurpfile files fprj_files.json \
            '{
              status: "success",
              run_id: $run_id,
              timestamp: $timestamp,
              file_count: ($files[0] | length),
              files: $files[0]
            }' > result.json
          
          # 打印结果便于调试
          cat result.json

      - name: Create result output
        id: set-output
        run: |
          # 读取JSON内容并设置为输出
          result=$(cat result.json)
          echo "result=$result" >> $GITHUB_OUTPUT
          echo "结果已设置为作业输出"
