name: Find FPRJ Files
on:
  repository_dispatch:
    types: [find-fprj-request]

jobs:
  find-fprj:
    runs-on: ubuntu-latest
    outputs:
      run_url: ${{ steps.upload.outputs.run_url }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Find .fprj files
        run: |
          find . -type f -name "*.fprj" > file_list.txt
          jq -R -s 'split("\n") | map(select(. != ""))' file_list.txt > fprj_files.json
          echo "Found $(jq -r 'length' fprj_files.json) .fprj files"

      - name: Prepare JSON result
        run: |
          jq -n \
            --arg run_id "$GITHUB_RUN_ID" \
            --arg timestamp "$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
            --slurpfile files fprj_files.json \
            '{
              status: "success",
              run_id: $run_id,
              timestamp: $timestamp,
              file_count: ($files[0] | length),
              files: $files[0]
            }' > result.json

      - name: Upload result as artifact
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: fprj-results
          path: result.json
          retention-days: 1  # 短期保留
          
      - name: Set run URL output
        run: |
          run_url="https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
          echo "run_url=$run_url" >> $GITHUB_OUTPUT
