name: Find FPRJ Files
on:
  workflow_dispatch:
  repository_dispatch:
    types: [find-fprj-request]

jobs:
  find-fprj:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.return-results.outputs.result }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Find .fprj files
        id: find-files
        run: |
          # 递归查找所有.fprj文件并输出为JSON数组
          find . -type f -name "*.fprj" | jq -R -n '[inputs]' > fprj_files.json
          echo "文件已保存到fprj_files.json"

      - name: Create result output
        id: return-results
        run: |
          # 从文件中读取生成的JSON
          json_result=$(cat fprj_files.json)
          
          # 创建包含完整响应的JSON
          response_json=$(jq -n \
            --arg run_id "$GITHUB_RUN_ID" \
            --argjson files "$json_result" \
            '{
              status: "success",
              run_id: $run_id,
              timestamp: (now | todate),
              file_count: ($files | length),
              files: $files
            }')
          
          # 设置作业输出
          echo "result=$response_json" >> $GITHUB_OUTPUT
          echo "结果已设置到输出"

      - name: Print result
        run: echo "${{ steps.return-results.outputs.result }}"
