name: Generate Watch Face
on:
  workflow_dispatch:
    inputs:
      input_json:
        description: 'JSON containing model path and image Base64'
        required: true

jobs:
  generate:
    runs-on: windows-latest
    permissions:
      contents: write
      
    steps:
      # 1. 检出代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. 解析JSON输入
      - name: Parse JSON input
        id: parse-json
        run: |
          $jsonInput = '${{ github.event.inputs.input_json }}' | ConvertFrom-Json
          echo "fprj_path=$($jsonInput.model)" >> $env:GITHUB_OUTPUT
          echo "image_base64=$($jsonInput.file)" >> $env:GITHUB_OUTPUT

      # 3. 准备项目文件
      - name: Prepare project
        run: |
          # 创建项目目录
          $projectDir = "project"
          New-Item -ItemType Directory -Path $projectDir -Force
          
          # 复制并重命名FPRJ文件
          Copy-Item -Path "${{ steps.parse-json.outputs.fprj_path }}" -Destination "$projectDir\fprj.fprj" -Force
          
          # 创建图片目录
          $imageDir = "$projectDir\images"
          New-Item -ItemType Directory -Path $imageDir -Force
          
          # 保存图片
          $bytes = [Convert]::FromBase64String('${{ steps.parse-json.outputs.image_base64 }}')
          [IO.File]::WriteAllBytes("$imageDir\pic.png", $bytes)

      # 4. 设置Python环境
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 5. 运行Python脚本
      - name: Run Python script
        run: |
          python compile_watchface.py
            # 在运行Python脚本后添加
      - name: Debug output file
        run: |
          $file = Get-ChildItem -Path "output" -Filter "*.face"
          if ($file) {
              Write-Host "Output file size: $($file.Length) bytes"
              # 输出文件头部
              $header = Get-Content -Path $file.FullName -Encoding Byte -TotalCount 32
              Write-Host "File header: $header"
          } else {
              Write-Error "No output file found"
          }

      # 6. 验证输出文件
      - name: Verify output file
        run: |
          if (Test-Path "output\*.face") {
              $file = Get-ChildItem -Path "output" -Filter "*.face"
              Write-Host "Output file exists: $($file.FullName)"
              Write-Host "File size: $($file.Length) bytes"
          } else {
              Write-Error "No output file found"
              exit 1
          }

      # 7. 创建Release并获取下载链接
      - name: Create Release and Get URL
        id: create-release
        uses: softprops/action-gh-release@v2
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          tag_name: "face-${{ github.run_id }}"
          files: output/*.face
          draft: false
          prerelease: false
      
    outputs:
      download_url: ${{ steps.create-release.outputs.url }}
